/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import Animations.MRUAnimation;
import Animations.MRUAAnimation;
import Animations.NewtonLawsAnimation;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Luis Carrioni
 */
public class AnimacionesPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnimacionesPanel
     */
    public AnimacionesPanel() {
        initComponents();
        setupAnimations();
    }

    private void setupAnimations() {
        // Inicializar las pestañas
        tabbedPane.removeAll();
        
        // Crear paneles de animación
        MRUAnimation mruAnimation = new MRUAnimation();
        MRUAAnimation mruaAnimation = new MRUAAnimation();
        NewtonLawsAnimation newtonAnimation = new NewtonLawsAnimation();
        
        // Configurar tamaños
        JPanel mruPanel = mruAnimation.getAnimationPanel();
        JPanel mruaPanel = mruaAnimation.getAnimationPanel();
        JPanel newtonPanel = newtonAnimation.getAnimationPanel();
        
        mruPanel.setPreferredSize(new Dimension(750, 500));
        mruaPanel.setPreferredSize(new Dimension(750, 500));
        newtonPanel.setPreferredSize(new Dimension(750, 500));
        
        // Agregar paneles a las pestañas
        tabbedPane.addTab("MRU", null, wrapInScrollPane(mruPanel), "Movimiento Rectilíneo Uniforme");
        tabbedPane.addTab("MRUA", null, wrapInScrollPane(mruaPanel), "Movimiento Rectilíneo Uniformemente Acelerado");
        tabbedPane.addTab("Leyes de Newton", null, wrapInScrollPane(newtonPanel), "Segunda Ley de Newton: F = m·a");
    }
    
    // Envuelve el panel en un JScrollPane para asegurar que se muestre completo
    private JScrollPane wrapInScrollPane(JPanel panel) {
        JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        return scrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(153, 255, 153));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("APP-FISICA - Animaciones");
        headerPanel.add(titleLabel);

        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        subtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitleLabel.setText("Visualización interactiva de conceptos físicos");
        headerPanel.add(subtitleLabel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setLayout(new java.awt.BorderLayout());

        tabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contentPanel.add(tabbedPane, java.awt.BorderLayout.CENTER);

        mainPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
