/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import java.awt.BorderLayout;

/**
 *
 * @author LENOVO
 */
public class Mrua extends javax.swing.JPanel {

    /**
     * Creates new form Mrua
     */
    public Mrua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnd2 = new javax.swing.JButton();
        btna = new javax.swing.JButton();
        btnvf = new javax.swing.JButton();
        btnvi = new javax.swing.JButton();
        pmrua = new javax.swing.JPanel();
        btnt2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/f.jpg"))); // NOI18N

        jLabel2.setText("Que Desea Calcular?");

        btnd2.setText("Distancia");
        btnd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnd2ActionPerformed(evt);
            }
        });

        btna.setText("Aceleracion");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });

        btnvf.setText("Velocidad Final");
        btnvf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvfActionPerformed(evt);
            }
        });

        btnvi.setText("Velocidad Inicial");
        btnvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pmruaLayout = new javax.swing.GroupLayout(pmrua);
        pmrua.setLayout(pmruaLayout);
        pmruaLayout.setHorizontalGroup(
            pmruaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pmruaLayout.setVerticalGroup(
            pmruaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnt2.setText("Tiempo");
        btnt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnd2)
                            .addComponent(btna)
                            .addComponent(btnvf)
                            .addComponent(btnvi)
                            .addComponent(btnt2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pmrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pmrua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvi))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnt2ActionPerformed
        Tiempo2 p = new Tiempo2();
        p.setSize(300,200);
        p.setLocation(0,0);
        
        pmrua.removeAll();
        pmrua.add(p,BorderLayout.CENTER);
        pmrua.revalidate();
        pmrua.repaint();
    }//GEN-LAST:event_btnt2ActionPerformed

    private void btnd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnd2ActionPerformed
        Distancia2 p = new Distancia2();
        p.setSize(300,200);
        p.setLocation(0,0);
        
        pmrua.removeAll();
        pmrua.add(p,BorderLayout.CENTER);
        pmrua.revalidate();
        pmrua.repaint();
    }//GEN-LAST:event_btnd2ActionPerformed

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
        Aceleracion p = new Aceleracion();
        p.setSize(300,200);
        p.setLocation(0,0);
        
        pmrua.removeAll();
        pmrua.add(p,BorderLayout.CENTER);
        pmrua.revalidate();
        pmrua.repaint();
    }//GEN-LAST:event_btnaActionPerformed

    private void btnvfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvfActionPerformed
        VelocidadFinal p = new VelocidadFinal();
        p.setSize(300,200);
        p.setLocation(0,0);
        
        pmrua.removeAll();
        pmrua.add(p,BorderLayout.CENTER);
        pmrua.revalidate();
        pmrua.repaint();
    }//GEN-LAST:event_btnvfActionPerformed

    private void btnviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviActionPerformed
        VelocidadInicial p = new VelocidadInicial();
        p.setSize(300,200);
        p.setLocation(0,0);
        
        pmrua.removeAll();
        pmrua.add(p,BorderLayout.CENTER);
        pmrua.revalidate();
        pmrua.repaint();
    }//GEN-LAST:event_btnviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btna;
    private javax.swing.JButton btnd2;
    private javax.swing.JButton btnt2;
    private javax.swing.JButton btnvf;
    private javax.swing.JButton btnvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pmrua;
    // End of variables declaration//GEN-END:variables
}
