/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import java.awt.BorderLayout;

import javax.swing.JButton;

/**
 *
 * @author LENOVO
 */
public class P2 extends javax.swing.JPanel {

    /**
     * Creates new form P2
     */
    public P2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnmru = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnmrua = new javax.swing.JButton();
        btnldn = new javax.swing.JButton();
        pe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAnimaciones = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        btnmru.setText("MRU");
        btnmru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmruActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("APP-FISICA");

        btnmrua.setText("MRUA");
        btnmrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmruaActionPerformed(evt);
            }
        });

        btnldn.setText("Leyes De Newton");
        btnldn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnldnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout peLayout = new javax.swing.GroupLayout(pe);
        pe.setLayout(peLayout);
        peLayout.setHorizontalGroup(
            peLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        peLayout.setVerticalGroup(
            peLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/20231121155455_0_1.png"))); // NOI18N

        btnAnimaciones.setText("Animaciones");
        btnAnimaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnmru)
                        .addGap(93, 93, 93)
                        .addComponent(btnmrua)
                        .addGap(75, 75, 75)
                        .addComponent(btnldn)
                        .addGap(74, 74, 74)
                        .addComponent(btnAnimaciones)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnldn)
                    .addComponent(btnmrua)
                    .addComponent(btnmru)
                    .addComponent(btnAnimaciones))
                .addGap(18, 18, 18)
                .addComponent(pe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmruActionPerformed
        Mru p = new Mru();
        p.setSize(955, 460);
        p.setLocation(0, 0);

        pe.removeAll();
        pe.add(p, BorderLayout.CENTER);
        pe.revalidate();
        pe.repaint();
    }//GEN-LAST:event_btnmruActionPerformed

    private void btnmruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmruaActionPerformed
        Mrua p = new Mrua();
        p.setSize(955, 460);
        p.setLocation(0, 0);

        pe.removeAll();
        pe.add(p, BorderLayout.CENTER);
        pe.revalidate();
        pe.repaint();
    }//GEN-LAST:event_btnmruaActionPerformed

    private void btnldnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnldnActionPerformed
        LeyesDeNewton p = new LeyesDeNewton();
        p.setSize(955, 460);
        p.setLocation(0, 0);

        pe.removeAll();
        pe.add(p, BorderLayout.CENTER);
        pe.revalidate();
        pe.repaint();
    }//GEN-LAST:event_btnldnActionPerformed

    private void btnAnimacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimacionesActionPerformed
        AnimacionesPanel animacionesPanel = new AnimacionesPanel();
        pe.removeAll();
        pe.setLayout(new BorderLayout());
        pe.add(animacionesPanel, BorderLayout.CENTER);
        pe.revalidate();
        pe.repaint();
    }//GEN-LAST:event_btnAnimacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimaciones;
    private javax.swing.JButton btnldn;
    private javax.swing.JButton btnmru;
    private javax.swing.JButton btnmrua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pe;
    // End of variables declaration//GEN-END:variables
}
